export const UPDATE_QUERY = 'UPDATE_QUERY';

export const EXECUTE_QUERY = 'EXECUTE_QUERY';
export const ON_EXECUTE_QUERY_END = 'ON_EXECUTE_QUERY_END';
export const ON_EXECUTE_QUERY_ERROR = 'ON_EXECUTE_QUERY_ERROR';

export const RESET_STATE = 'RESET_STATE';

export const START_RECOGNITION = 'START_RECOGNITION';
export const ON_RECOGNITION_ERROR = 'ON_RECOGNITION_ERROR';