#!/bin/bash

BLACK=`python -c "import sys; print('True' if sys.version_info >= (3,6) else '')"`

FLAKE8_OPTIONS=""

if [ "$MM_EXTRAS" == "true" ]; then
  PYLINT_OPTIONS=""
else
  PYLINT_OPTIONS="--ignore mindmeld/bot"
fi

black --check .

flake8 mindmeld tests $FLAKE8_OPTIONS
pylint mindmeld $PYLINT_OPTIONS
