# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class Transcript(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, transcript: str = None, confidence: float = None):  # noqa: E501
        """Transcript - a model defined in Swagger

        :param transcript: The transcript of this Transcript.  # noqa: E501
        :type transcript: str
        :param confidence: The confidence of this Transcript.  # noqa: E501
        :type confidence: float
        """
        self.swagger_types = {"transcript": str, "confidence": float}

        self.attribute_map = {"transcript": "transcript", "confidence": "confidence"}

        self._transcript = transcript
        self._confidence = confidence

    @classmethod
    def from_dict(cls, dikt) -> "Transcript":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Transcript of this Transcript.  # noqa: E501
        :rtype: Transcript
        """
        return util.deserialize_model(dikt, cls)

    @property
    def transcript(self) -> str:
        """Gets the transcript of this Transcript.

        Transcription  # noqa: E501

        :return: The transcript of this Transcript.
        :rtype: str
        """
        return self._transcript

    @transcript.setter
    def transcript(self, transcript: str):
        """Sets the transcript of this Transcript.

        Transcription  # noqa: E501

        :param transcript: The transcript of this Transcript.
        :type transcript: str
        """

        self._transcript = transcript

    @property
    def confidence(self) -> float:
        """Gets the confidence of this Transcript.

        Transcription confidence  # noqa: E501

        :return: The confidence of this Transcript.
        :rtype: float
        """
        return self._confidence

    @confidence.setter
    def confidence(self, confidence: float):
        """Sets the confidence of this Transcript.

        Transcription confidence  # noqa: E501

        :param confidence: The confidence of this Transcript.
        :type confidence: float
        """

        self._confidence = confidence
